[features]
seeds = false
skip-lint = false
[programs.localnet]
solbank = "FKonoaK2EEFhD2arreKsnDfjFP9Xk7V5j2jsXZa1GHRq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/toastx/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
